name: kurumi
description: Unofficial anilist client

publish_to: "none"

version: 1.15.0+49

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  anilist:
    path: "../anilist"
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^4.0.1
  go_router: ^14.2.2
  google_fonts: ^6.1.0
  url_launcher: ^6.1.10
  flutter_web_auth_2: ^3.0.1
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.2.0
  shared_preferences: ^2.0.18
  line_icons: ^2.0.1
  lottie: ^3.1.2
  cached_network_image: ^3.2.3
  flutter_launcher_icons: ^0.13.1
  ferry: ^0.14.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.0.1
  shimmer: ^3.0.0
  ionicons: ^0.2.2
  card_swiper: ^3.0.1
  intl: ^0.19.0
  flutter_markdown: ^0.7.3
  screenshot: ^3.0.0
  path_provider: ^2.0.14
  zoom_widget: ^2.0.1
  upgrader: ^10.3.0
  logger: ^2.0.2
  flutter_inappwebview: ^6.0.0
  share_plus: ^7.2.1
  flutter_animate: ^4.2.0+1
  phosphor_flutter: ^2.0.1
  syncfusion_flutter_charts: ^26.2.7
  flutter_phoenix: ^1.1.1
  workmanager: ^0.5.2
  flutter_local_notifications: ^17.2.1+2
  http: ^1.2.2
  gap: ^3.0.1
  reorderable_grid_view: ^2.2.8
  xml2json: ^6.2.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  go_router_builder: ^2.3.3
  build_runner: ^2.4.6

flutter_gen:
  output: lib/src/core/assets/

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true

  # colors:
  #   inputs:
  #     - assets/color/colors.xml

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/meta/ninja.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/splash/
    - assets/lotties/
    - assets/gifs/
    - assets/meta/ninja.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
